### ISSUE TITLE
Need Dequeue to Return Node not Item

### ISSUE THREAD

**Issue by Azurekuz** [Legit-SpaceHunters/space-bounty-agency#4]
As the title says, I need the LinkedPriorityQueue to return the entire node, and allow me to read the node's weight so that I can can have the ships be able to count up their power.

**Comment by Darquis** [comment]
The priority of the node should be the exact same as the ship's battle power. I imagine returning a node would be inefficient since the entire node is copied instead of just the ship. (Note, the functions return copies, not references. This is important for ships since the ships are constantly being destroyed and newly hired)

**Comment by Azurekuz** [comment]
Yeah, but isn't the ships battle power calculated from the individual priorities of the crew members?

**Comment by Darquis** [comment]
yeah, same idea. shipQueue.getCadet().getPower()

**Comment by Darquis** [comment]
otherwise, we would have to copy the entire node -> shipQueue.getNode()->priority

**Comment by Azurekuz** [comment]
I see. I added an accessor method for the Space Cadet to return their power/battleranking. Thanks!

**Comment by Darquis** [comment]
Awesome. I'm closing the issue for now. When I get some time, I'm going to implement the history, event, and battle classes. (btw, when ships enter a battle, use the Battle constructor. That way the class can both be in charge of the simulation and record summary information)
